x-php-attributes: &php-attributes
  build:
    context: .
    target: base #availables targets: base, xdebug @see Dockerfile stages
  volumes:
#    - .docker/conf.d/50_xdebug.ini:/etc/php85/conf.d/50_xdebug.ini
    - .docker/conf.d/opcache.ini:/etc/php85/conf.d/opcache.ini
    - .docker/php.ini:/etc/php85/php.ini
    - .docker/php-fpm.d/www.conf:/etc/php85/php-fpm.d/www.conf
    - fpm-sock:/var/run/php
  extra_hosts:
    - host.docker.internal:host-gateway


services:
  php: *php-attributes

volumes:
  fpm-sock: